### PR TITLE
Merge @ksandom's 'tips & tricks' repo

### LINKED ISSUE #19: Add link to @ksandom's blog for Astro tips.
As per discussion with @ksandom on Discord, looking to add a link to their blog to this wiki.

Related to: #20.

See: https://www.randomksandom.com/astro/

### LINKED ISSUE #20: Copy @ksandom's repository Markdown to the wiki.
As per discussion with @ksandom on Discord, looking to merge [this](https://github.com/ksandom/astroTipsAndTricks) repo with this wiki.

Related to #19.

### PR DESCRIPTION
**Pull request by shymega**
As per #19, and #20, I've patched this repo with the files from @ksandom's tips and tricks repository.

- Rearrange folders to match existing directory

Closes #19, and #20.

### CODE REVIEW

**Comment by ksandom** [comment]
Looks great. Go for it.

**Comment by shymega** [comment]
@ZimbiX Any objections?

**Comment by ZimbiX** [comment]
G'day guys.

To be honest, I don't really think there's much value in merging in @ksandom's repo. I'd probably just link to it and his blog.

The `scrcpy` document doesn't seem that useful to me, as in his article he mentions it's super low FPS and high latency. I reckon what would be more useful is mention of DisplayLink adapters working; I haven't tried, so can't confirm, but I do recall people saying that.

And the virtualisation/containerisation page is not Planet-specific.

Likewise, I don't think https://github.com/shymega/planet-devices/commit/d7ca807958c31d83d235d8d490cd43408a095d66 was a good idea.

I think it's great that these things are written up somewhere; I just don't think here is the place for it. imho, let's keep the wiki to information directly related to Planet Computers' devices, and that which would be reasonably useful to others.

I reckon we should instead just do https://github.com/shymega/planet-devices-wiki-prs/issues/19 - link to the blog, probably from the 'Community and Resources' page. If we're adding a section there for blogs/sites, I'm sure there are others we could include too, e.g. [ssipa's](http://ssipa.web.fc2.com/index.html).

And @ksandom, if you want to contribute to the wiki in future, feel free to make your own PRs :wink:

**Comment by ksandom** [comment]
@ZimbiX Good points. In particular, my repo is very dated now.

I have already added a link back to the planet-devices repo [on my old repo](https://github.com/ksandom/astroTipsAndTricks/tree/main#astrotipsandtricks). And just now I've added a link specifically to the wiki.

@shymega You're welcome to revert https://github.com/shymega/planet-devices/commit/d7ca807958c31d83d235d8d490cd43408a095d66 if you think that that is the best way forwards for the repo.

**Comment by shymega** [comment]
Fair enough, I'll revert now on `planet-devices`, and close this PR.

@ZimbiX thanks for your input :+1:

@ksandom If you want to make a PR to the wiki to add the DisplayPort info, that'd be welcome :100:

**Comment by ksandom** [comment]
> @ksandom If you want to make a PR to the wiki to add the DisplayPort info, that'd be welcome :100: 

@shymega  Something that became apparent yesterday when I was interacting with people in #issues on discord; is that assumptions/observations that were correct for the original firmware, are not necessarily true for the new firmware. An example relevant to the display adapter is that with the original firmware, you need to reboot to activate it. Maybe that's not true any more.

I don't know when I will get my Astro back; so I recommend that someone else writes it if they'd like to have it sooner.

The gist of it is:

* Gemini HDMI adapter works with the Astro.
* Plug it in on the left side of the device.  (I'm questioning myself now, do verify which side it is.)
* Reboot the device.
* You can plug in a USB hub with mouse/keyboard/storage etc on the other port.
* Don't unplug anything while the device is shutting down, otherwise it will reboot. You can do so either before shutting down, or after the device has **fully** shutdown. (ie not just turned off the screen, but actually finished shutting down.)
  * If I remember correctly; once you have unplugged the HDMI adapter, you will need to reboot the device to get it to work again.

\[Edit: Typos.\]

**Comment by shymega** [comment]
> > @ksandom If you want to make a PR to the wiki to add the DisplayPort info, that'd be welcome 100
> 
> @shymega Something that became apparent yesterday when I was interacting with people in #issues on discord; is that assumptions/observations that were correct for the original firmware, are not necessarily true for the new firmware. An example relevant to the display adapter is that with the original firmware, you need to reboot to activate it. Maybe that's not true any more.
> 
> I don't know when I will get my Astro back; so I recommend that someone else writes it if they'd like to have it sooner.
> 
> The gist of it is:
> 
> * Gemini HDMI adapter works with the Astro.
> * Plug it in on the left side of the device.  (I'm questioning myself now, do verify which side it is.)
> * Reboot the device.
> * You can plug in a USB hub with mouse/keyboard/storage etc on the other port.
> * Don't unplug anything while the device is shutting down, otherwise it will reboot. You can do so either before shutting down, or after the device has **fully** shutdown. (ie not just turned off the screen, but actually finished shutting down.)
>   
>   * If I remember correctly; once you have unplugged the HDMI adapter, you will need to reboot the device to get it to work again.
> 
> [Edit: Typos.]

OK - could you create an issue for this, so we have it on the tracker? This current repository is a good place.

**Comment by ksandom** [comment]
> OK - could you create an issue for this, so we have it on the tracker? This current repository is a good place.

Sure. I've [just added that issue](https://github.com/shymega/planet-devices-wiki-prs/issues/26) now.

**Pull request closed without merging**
